### ISSUE TITLE
Concurrently running workflows for the same commit cause "Unable to proceed. HTTP PUT failed: [403] Updating the content of a complete result is not allowed."

### ISSUE THREAD

**Issue by amezin** [testspace-com/setup-testspace#14]
A workflow configured to run on both pushes and pull requests:

```
on:
  push:
  pull_request:
```

Will run twice for pull requests from the same repository (once for push, once for pull request).

If this action is used in a such workflow, upload will fail:

```
Unable to proceed. HTTP PUT failed: [403] Updating the content of a complete result is not allowed.
```

It will happen even if jobs of one of these workflows will be skipped.

Example: https://github.com/ddterm/gnome-shell-extension-ddterm/pull/148

**Comment by ivailop** [comment]
Thanks for reporting the problem. It appears to be related to your conditional "skipping" of `pull_request` runs...

A patch has been applied to address the problem. Please let us know if are still experience the issue.

**Comment by amezin** [comment]
Yes, seems to be working now, thank you.

> It appears to be related to your conditional "skipping" of pull_request runs...

If I'm not mistaken, I also observed the same issue without any skipping - i.e. with

```
on:
  push:
  pull_request:
```

without any `if`s. It just wasn't 100% reproducible. But right now I can't find these workflow runs... So maybe I'm wrong, and it didn't happen.

**Comment by ivailop** [comment]
> > It appears to be related to your conditional "skipping" of pull_request runs...
> 
> If I'm not mistaken, I also observed the same issue without any skipping - i.e. with

You are right, it was possible to occur without skipping. The skipping made the problem very obvious.
