### ISSUE TITLE
'testspace-analytics' check sometimes stays in 'queued' state indefinitely

### ISSUE THREAD

**Issue by amezin** [testspace-com/setup-testspace#15]
After GitHub Actions workflow completes, sometimes "testspace-analytics" remains in "queued" state.

Usually, pushing to that branch again, or manually restarting the workflow "fixes" testspace check - i. e. it completes for the new CI run.

But now I have a pull request where "testspace-analytics" never completes, even after subsequent pushes or CI workflow restarts: https://github.com/ddterm/gnome-shell-extension-ddterm/pull/250

**Comment by ivailop** [comment]
It looks like the problem is related to reusing the same branch-name multiple times. We'll investigate further and try to fix in the upcoming release.

**Comment by munderseth** [comment]
@amezin in the meantime you can manually `Complete` the results via the hamburger menu:

- https://ddterm.testspace.com/spaces/195410/result_sets 

![image](https://user-images.githubusercontent.com/1229367/204559045-34704eae-f912-4bee-9656-b06707e2b677.png)

**Comment by ivailop** [comment]
A fix for the bug has been deployed.
